"""Standard industry catalog for seeding the industries table.

Based on the Active Vibe Models reference spreadsheet (columns A-D).
Each entry provides: display name, short business name (used by the notebook),
a brief description (vibe instruction seed text), and notable businesses.
"""

INDUSTRY_CATALOG: list[dict[str, str]] = [
    {
        "name": "Retail & E-Commerce",
        "short_name": "Retail",
        "description": "Consumer-facing retail and e-commerce businesses including omnichannel, marketplace, and direct-to-consumer models.",
        "notable_businesses": "Amazon, Walmart, Target, Shopify",
    },
    {
        "name": "Financial Services - Banking",
        "short_name": "Banking",
        "description": "Commercial and retail banking, including deposits, lending, payments, and treasury services.",
        "notable_businesses": "JPMorgan Chase, Bank of America, Wells Fargo",
    },
    {
        "name": "Financial Services - Insurance",
        "short_name": "Insurance",
        "description": "Property & casualty, life, health, and specialty insurance including underwriting, claims, and actuarial.",
        "notable_businesses": "State Farm, Allstate, AIG, Progressive",
    },
    {
        "name": "Financial Services - Capital Markets",
        "short_name": "Capital Markets",
        "description": "Investment banking, trading, asset management, and securities services.",
        "notable_businesses": "Goldman Sachs, Morgan Stanley, BlackRock",
    },
    {
        "name": "Healthcare - Provider",
        "short_name": "Healthcare Provider",
        "description": "Hospitals, clinics, and health systems including patient care, clinical operations, and revenue cycle.",
        "notable_businesses": "HCA Healthcare, Kaiser Permanente, Mayo Clinic",
    },
    {
        "name": "Healthcare - Payer",
        "short_name": "Healthcare Payer",
        "description": "Health insurance and managed care including enrollment, claims adjudication, and member services.",
        "notable_businesses": "UnitedHealth, Anthem, Cigna, Humana",
    },
    {
        "name": "Healthcare - Life Sciences",
        "short_name": "Life Sciences",
        "description": "Pharmaceutical, biotech, and medical device companies including R&D, clinical trials, and commercialization.",
        "notable_businesses": "Pfizer, Johnson & Johnson, Roche, Merck",
    },
    {
        "name": "Manufacturing - Discrete",
        "short_name": "Discrete Manufacturing",
        "description": "Discrete manufacturing of assembled products including automotive, aerospace, electronics, and industrial equipment.",
        "notable_businesses": "Toyota, Boeing, Siemens, General Electric",
    },
    {
        "name": "Manufacturing - Process",
        "short_name": "Process Manufacturing",
        "description": "Process manufacturing including chemicals, food & beverage, pharmaceuticals, and continuous production.",
        "notable_businesses": "Dow Chemical, Nestlé, Procter & Gamble",
    },
    {
        "name": "Telecommunications",
        "short_name": "Telecom",
        "description": "Wireline, wireless, and broadband telecommunications including network operations, billing, and customer management.",
        "notable_businesses": "AT&T, Verizon, T-Mobile, Comcast",
    },
    {
        "name": "Media & Entertainment",
        "short_name": "Media",
        "description": "Content creation, distribution, streaming, gaming, and advertising across digital and traditional media.",
        "notable_businesses": "Disney, Netflix, Warner Bros, Spotify",
    },
    {
        "name": "Energy - Oil & Gas",
        "short_name": "Oil and Gas",
        "description": "Upstream exploration and production, midstream transportation, and downstream refining and marketing.",
        "notable_businesses": "ExxonMobil, Shell, Chevron, BP",
    },
    {
        "name": "Energy - Utilities",
        "short_name": "Utilities",
        "description": "Electric, gas, and water utilities including generation, transmission, distribution, and customer billing.",
        "notable_businesses": "Duke Energy, Southern Company, Exelon",
    },
    {
        "name": "Energy - Renewables",
        "short_name": "Renewables",
        "description": "Renewable energy generation, storage, and grid integration including solar, wind, and battery systems.",
        "notable_businesses": "NextEra Energy, Vestas, First Solar",
    },
    {
        "name": "Transportation & Logistics",
        "short_name": "Logistics",
        "description": "Freight, shipping, last-mile delivery, warehousing, and supply chain logistics.",
        "notable_businesses": "FedEx, UPS, DHL, Maersk",
    },
    {
        "name": "Airlines & Aviation",
        "short_name": "Airlines",
        "description": "Passenger and cargo airlines including route planning, fleet management, and loyalty programs.",
        "notable_businesses": "Delta, United, Emirates, Southwest",
    },
    {
        "name": "Automotive",
        "short_name": "Automotive",
        "description": "Automotive OEMs, dealerships, and mobility services including connected vehicles and EV infrastructure.",
        "notable_businesses": "Tesla, Toyota, Volkswagen, GM",
    },
    {
        "name": "Technology - SaaS",
        "short_name": "SaaS",
        "description": "Software-as-a-service businesses including product-led growth, subscription management, and platform operations.",
        "notable_businesses": "Salesforce, ServiceNow, Atlassian, Zoom",
    },
    {
        "name": "Technology - Semiconductor",
        "short_name": "Semiconductor",
        "description": "Semiconductor design, fabrication, and testing including chip architecture and fab operations.",
        "notable_businesses": "NVIDIA, Intel, TSMC, AMD",
    },
    {
        "name": "Technology - Cloud & Infrastructure",
        "short_name": "Cloud Infrastructure",
        "description": "Cloud computing, data centers, and infrastructure services including IaaS, PaaS, and managed services.",
        "notable_businesses": "AWS, Azure, Google Cloud, Snowflake",
    },
    {
        "name": "Government - Federal",
        "short_name": "Federal Government",
        "description": "Federal government agencies including defense, civilian services, and regulatory bodies.",
        "notable_businesses": "DoD, VA, IRS, NASA",
    },
    {
        "name": "Government - State & Local",
        "short_name": "State Local Government",
        "description": "State and local government including public safety, transportation, education, and social services.",
        "notable_businesses": "State DOTs, City of New York, County of LA",
    },
    {
        "name": "Education - Higher Ed",
        "short_name": "Higher Education",
        "description": "Colleges, universities, and research institutions including enrollment, student success, and research administration.",
        "notable_businesses": "Harvard, MIT, Stanford, UC System",
    },
    {
        "name": "Education - K-12",
        "short_name": "K12 Education",
        "description": "K-12 school districts and education technology including student information systems and curriculum management.",
        "notable_businesses": "LAUSD, NYC DOE, Khan Academy",
    },
    {
        "name": "Real Estate & Construction",
        "short_name": "Real Estate",
        "description": "Commercial and residential real estate including development, property management, and construction.",
        "notable_businesses": "CBRE, Prologis, Brookfield, Lennar",
    },
    {
        "name": "Hospitality & Travel",
        "short_name": "Hospitality",
        "description": "Hotels, resorts, restaurants, and travel services including booking, revenue management, and loyalty.",
        "notable_businesses": "Marriott, Hilton, Airbnb, Booking.com",
    },
    {
        "name": "Agriculture & Food",
        "short_name": "Agriculture",
        "description": "Farming, agribusiness, food processing, and agricultural technology including precision agriculture.",
        "notable_businesses": "Cargill, John Deere, ADM, Bayer Crop",
    },
    {
        "name": "Mining & Metals",
        "short_name": "Mining",
        "description": "Mining, metals processing, and mineral extraction including exploration, operations, and environmental management.",
        "notable_businesses": "BHP, Rio Tinto, Vale, Glencore",
    },
    {
        "name": "Pharmaceutical Distribution",
        "short_name": "Pharma Distribution",
        "description": "Pharmaceutical wholesale distribution, pharmacy benefit management, and drug supply chain.",
        "notable_businesses": "McKesson, AmerisourceBergen, Cardinal Health",
    },
    {
        "name": "Professional Services",
        "short_name": "Professional Services",
        "description": "Consulting, accounting, legal, and engineering services including project delivery and workforce management.",
        "notable_businesses": "Deloitte, Accenture, McKinsey, KPMG",
    },
    {
        "name": "Nonprofit & NGO",
        "short_name": "Nonprofit",
        "description": "Charitable organizations, foundations, and NGOs including fundraising, program management, and impact measurement.",
        "notable_businesses": "Red Cross, United Way, WHO, UNICEF",
    },
    {
        "name": "Sports & Entertainment",
        "short_name": "Sports",
        "description": "Professional sports leagues, teams, venues, and live entertainment including ticketing and fan engagement.",
        "notable_businesses": "NFL, NBA, Live Nation, FIFA",
    },
    {
        "name": "Fashion & Luxury",
        "short_name": "Fashion",
        "description": "Fashion, luxury goods, and apparel including design, merchandising, and direct-to-consumer retail.",
        "notable_businesses": "LVMH, Nike, Zara (Inditex), H&M",
    },
    {
        "name": "Consumer Packaged Goods",
        "short_name": "CPG",
        "description": "Fast-moving consumer goods including brand management, supply chain, and trade promotion.",
        "notable_businesses": "Procter & Gamble, Unilever, Coca-Cola, PepsiCo",
    },
    {
        "name": "Gaming & Gambling",
        "short_name": "Gaming",
        "description": "Video games, casinos, sports betting, and online gaming including player analytics and regulatory compliance.",
        "notable_businesses": "MGM, DraftKings, Electronic Arts, Activision",
    },
    {
        "name": "Defense & Aerospace",
        "short_name": "Defense",
        "description": "Defense contractors, aerospace manufacturers, and space technology including procurement and program management.",
        "notable_businesses": "Lockheed Martin, Raytheon, Northrop Grumman",
    },
    {
        "name": "Shipping & Maritime",
        "short_name": "Maritime",
        "description": "Ocean shipping, port operations, and maritime logistics including fleet management and customs.",
        "notable_businesses": "Maersk, MSC, CMA CGM, DP World",
    },
    {
        "name": "Fintech & Payments",
        "short_name": "Fintech",
        "description": "Digital payments, neobanks, lending platforms, and financial technology infrastructure.",
        "notable_businesses": "Stripe, Square, PayPal, Plaid",
    },
    {
        "name": "Cybersecurity",
        "short_name": "Cybersecurity",
        "description": "Security software, managed security services, and threat intelligence including SOC operations.",
        "notable_businesses": "CrowdStrike, Palo Alto Networks, Fortinet",
    },
    {
        "name": "Supply Chain & Procurement",
        "short_name": "Supply Chain",
        "description": "Supply chain management, procurement platforms, and sourcing including vendor management and spend analytics.",
        "notable_businesses": "Coupa, SAP Ariba, Jaggaer, GEP",
    },
]
