/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as SidebarIndexRouteImport } from './../routes/_sidebar/index'
import { Route as SidebarBusinessesRouteImport } from './../routes/_sidebar/businesses'
import { Route as SidebarHelpRouteImport } from './../routes/_sidebar/help'
import { Route as SidebarIndustriesRouteImport } from './../routes/_sidebar/industries'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarSettingsRouteImport } from './../routes/_sidebar/settings'
import { Route as SidebarBusinessesIndexRouteImport } from './../routes/_sidebar/businesses.index'
import { Route as SidebarBusinessesBusinessIdRouteImport } from './../routes/_sidebar/businesses.$businessId'
import { Route as SidebarBusinessesNewRouteImport } from './../routes/_sidebar/businesses.new'
import { Route as SidebarHelpIndexRouteImport } from './../routes/_sidebar/help.index'
import { Route as SidebarHelpTopicRouteImport } from './../routes/_sidebar/help.$topic'
import { Route as SidebarIndustriesIndexRouteImport } from './../routes/_sidebar/industries.index'
import { Route as SidebarIndustriesNewRouteImport } from './../routes/_sidebar/industries.new'
import { Route as SidebarBusinessesBusinessIdIndexRouteImport } from './../routes/_sidebar/businesses.$businessId.index'
import { Route as SidebarBusinessesBusinessIdEditRouteImport } from './../routes/_sidebar/businesses.$businessId.edit'
import { Route as SidebarBusinessesBusinessIdExplorerRouteImport } from './../routes/_sidebar/businesses.$businessId.explorer'
import { Route as SidebarBusinessesBusinessIdRunsRouteImport } from './../routes/_sidebar/businesses.$businessId.runs'
import { Route as SidebarBusinessesBusinessIdModelVersionRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version'
import { Route as SidebarBusinessesBusinessIdRunsIndexRouteImport } from './../routes/_sidebar/businesses.$businessId.runs.index'
import { Route as SidebarBusinessesBusinessIdRunsRunIdRouteImport } from './../routes/_sidebar/businesses.$businessId.runs.$runId'
import { Route as SidebarBusinessesBusinessIdRunsNewRouteImport } from './../routes/_sidebar/businesses.$businessId.runs.new'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeIndexRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.index'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.$domainName'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeInputsRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.inputs'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.$domainName.index'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.$domainName.$productName'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.inputs.index'
import { Route as SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRouteImport } from './../routes/_sidebar/businesses.$businessId.model.$version.$scope.inputs.$inputId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarBusinessesRoute = SidebarBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarHelpRoute = SidebarHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarIndustriesRoute = SidebarIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSettingsRoute = SidebarSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarBusinessesIndexRoute = SidebarBusinessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarBusinessesRoute,
} as any)
const SidebarBusinessesBusinessIdRoute =
  SidebarBusinessesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => SidebarBusinessesRoute,
  } as any)
const SidebarBusinessesNewRoute = SidebarBusinessesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SidebarBusinessesRoute,
} as any)
const SidebarHelpIndexRoute = SidebarHelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarHelpRoute,
} as any)
const SidebarHelpTopicRoute = SidebarHelpTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => SidebarHelpRoute,
} as any)
const SidebarIndustriesIndexRoute = SidebarIndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarIndustriesRoute,
} as any)
const SidebarIndustriesNewRoute = SidebarIndustriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SidebarIndustriesRoute,
} as any)
const SidebarBusinessesBusinessIdIndexRoute =
  SidebarBusinessesBusinessIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarBusinessesBusinessIdRoute,
  } as any)
const SidebarBusinessesBusinessIdEditRoute =
  SidebarBusinessesBusinessIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => SidebarBusinessesBusinessIdRoute,
  } as any)
const SidebarBusinessesBusinessIdExplorerRoute =
  SidebarBusinessesBusinessIdExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => SidebarBusinessesBusinessIdRoute,
  } as any)
const SidebarBusinessesBusinessIdRunsRoute =
  SidebarBusinessesBusinessIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => SidebarBusinessesBusinessIdRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionRoute =
  SidebarBusinessesBusinessIdModelVersionRouteImport.update({
    id: '/model/$version',
    path: '/model/$version',
    getParentRoute: () => SidebarBusinessesBusinessIdRoute,
  } as any)
const SidebarBusinessesBusinessIdRunsIndexRoute =
  SidebarBusinessesBusinessIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarBusinessesBusinessIdRunsRoute,
  } as any)
const SidebarBusinessesBusinessIdRunsRunIdRoute =
  SidebarBusinessesBusinessIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => SidebarBusinessesBusinessIdRunsRoute,
  } as any)
const SidebarBusinessesBusinessIdRunsNewRoute =
  SidebarBusinessesBusinessIdRunsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => SidebarBusinessesBusinessIdRunsRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionScopeRoute =
  SidebarBusinessesBusinessIdModelVersionScopeRouteImport.update({
    id: '/$scope',
    path: '/$scope',
    getParentRoute: () => SidebarBusinessesBusinessIdModelVersionRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionScopeIndexRoute =
  SidebarBusinessesBusinessIdModelVersionScopeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarBusinessesBusinessIdModelVersionScopeRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute =
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteImport.update({
    id: '/$domainName',
    path: '/$domainName',
    getParentRoute: () => SidebarBusinessesBusinessIdModelVersionScopeRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionScopeInputsRoute =
  SidebarBusinessesBusinessIdModelVersionScopeInputsRouteImport.update({
    id: '/inputs',
    path: '/inputs',
    getParentRoute: () => SidebarBusinessesBusinessIdModelVersionScopeRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute =
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute,
    } as any,
  )
const SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute =
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRouteImport.update(
    {
      id: '/$productName',
      path: '/$productName',
      getParentRoute: () =>
        SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute,
    } as any,
  )
const SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute =
  SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      SidebarBusinessesBusinessIdModelVersionScopeInputsRoute,
  } as any)
const SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute =
  SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRouteImport.update({
    id: '/$inputId',
    path: '/$inputId',
    getParentRoute: () =>
      SidebarBusinessesBusinessIdModelVersionScopeInputsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarIndexRoute
  '/businesses': typeof SidebarBusinessesRouteWithChildren
  '/help': typeof SidebarHelpRouteWithChildren
  '/industries': typeof SidebarIndustriesRouteWithChildren
  '/profile': typeof SidebarProfileRoute
  '/settings': typeof SidebarSettingsRoute
  '/businesses/$businessId': typeof SidebarBusinessesBusinessIdRouteWithChildren
  '/businesses/new': typeof SidebarBusinessesNewRoute
  '/help/$topic': typeof SidebarHelpTopicRoute
  '/industries/new': typeof SidebarIndustriesNewRoute
  '/businesses/': typeof SidebarBusinessesIndexRoute
  '/help/': typeof SidebarHelpIndexRoute
  '/industries/': typeof SidebarIndustriesIndexRoute
  '/businesses/$businessId/edit': typeof SidebarBusinessesBusinessIdEditRoute
  '/businesses/$businessId/explorer': typeof SidebarBusinessesBusinessIdExplorerRoute
  '/businesses/$businessId/runs': typeof SidebarBusinessesBusinessIdRunsRouteWithChildren
  '/businesses/$businessId/': typeof SidebarBusinessesBusinessIdIndexRoute
  '/businesses/$businessId/model/$version': typeof SidebarBusinessesBusinessIdModelVersionRouteWithChildren
  '/businesses/$businessId/runs/$runId': typeof SidebarBusinessesBusinessIdRunsRunIdRoute
  '/businesses/$businessId/runs/new': typeof SidebarBusinessesBusinessIdRunsNewRoute
  '/businesses/$businessId/runs/': typeof SidebarBusinessesBusinessIdRunsIndexRoute
  '/businesses/$businessId/model/$version/$scope': typeof SidebarBusinessesBusinessIdModelVersionScopeRouteWithChildren
  '/businesses/$businessId/model/$version/$scope/$domainName': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteWithChildren
  '/businesses/$businessId/model/$version/$scope/inputs': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsRouteWithChildren
  '/businesses/$businessId/model/$version/$scope/': typeof SidebarBusinessesBusinessIdModelVersionScopeIndexRoute
  '/businesses/$businessId/model/$version/$scope/$domainName/$productName': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute
  '/businesses/$businessId/model/$version/$scope/inputs/$inputId': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute
  '/businesses/$businessId/model/$version/$scope/$domainName/': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute
  '/businesses/$businessId/model/$version/$scope/inputs/': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof SidebarProfileRoute
  '/settings': typeof SidebarSettingsRoute
  '/': typeof SidebarIndexRoute
  '/businesses/new': typeof SidebarBusinessesNewRoute
  '/help/$topic': typeof SidebarHelpTopicRoute
  '/industries/new': typeof SidebarIndustriesNewRoute
  '/businesses': typeof SidebarBusinessesIndexRoute
  '/help': typeof SidebarHelpIndexRoute
  '/industries': typeof SidebarIndustriesIndexRoute
  '/businesses/$businessId/edit': typeof SidebarBusinessesBusinessIdEditRoute
  '/businesses/$businessId/explorer': typeof SidebarBusinessesBusinessIdExplorerRoute
  '/businesses/$businessId': typeof SidebarBusinessesBusinessIdIndexRoute
  '/businesses/$businessId/model/$version': typeof SidebarBusinessesBusinessIdModelVersionRouteWithChildren
  '/businesses/$businessId/runs/$runId': typeof SidebarBusinessesBusinessIdRunsRunIdRoute
  '/businesses/$businessId/runs/new': typeof SidebarBusinessesBusinessIdRunsNewRoute
  '/businesses/$businessId/runs': typeof SidebarBusinessesBusinessIdRunsIndexRoute
  '/businesses/$businessId/model/$version/$scope': typeof SidebarBusinessesBusinessIdModelVersionScopeIndexRoute
  '/businesses/$businessId/model/$version/$scope/$domainName/$productName': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute
  '/businesses/$businessId/model/$version/$scope/inputs/$inputId': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute
  '/businesses/$businessId/model/$version/$scope/$domainName': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute
  '/businesses/$businessId/model/$version/$scope/inputs': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/businesses': typeof SidebarBusinessesRouteWithChildren
  '/_sidebar/help': typeof SidebarHelpRouteWithChildren
  '/_sidebar/industries': typeof SidebarIndustriesRouteWithChildren
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/settings': typeof SidebarSettingsRoute
  '/_sidebar/': typeof SidebarIndexRoute
  '/_sidebar/businesses/$businessId': typeof SidebarBusinessesBusinessIdRouteWithChildren
  '/_sidebar/businesses/new': typeof SidebarBusinessesNewRoute
  '/_sidebar/help/$topic': typeof SidebarHelpTopicRoute
  '/_sidebar/industries/new': typeof SidebarIndustriesNewRoute
  '/_sidebar/businesses/': typeof SidebarBusinessesIndexRoute
  '/_sidebar/help/': typeof SidebarHelpIndexRoute
  '/_sidebar/industries/': typeof SidebarIndustriesIndexRoute
  '/_sidebar/businesses/$businessId/edit': typeof SidebarBusinessesBusinessIdEditRoute
  '/_sidebar/businesses/$businessId/explorer': typeof SidebarBusinessesBusinessIdExplorerRoute
  '/_sidebar/businesses/$businessId/runs': typeof SidebarBusinessesBusinessIdRunsRouteWithChildren
  '/_sidebar/businesses/$businessId/': typeof SidebarBusinessesBusinessIdIndexRoute
  '/_sidebar/businesses/$businessId/model/$version': typeof SidebarBusinessesBusinessIdModelVersionRouteWithChildren
  '/_sidebar/businesses/$businessId/runs/$runId': typeof SidebarBusinessesBusinessIdRunsRunIdRoute
  '/_sidebar/businesses/$businessId/runs/new': typeof SidebarBusinessesBusinessIdRunsNewRoute
  '/_sidebar/businesses/$businessId/runs/': typeof SidebarBusinessesBusinessIdRunsIndexRoute
  '/_sidebar/businesses/$businessId/model/$version/$scope': typeof SidebarBusinessesBusinessIdModelVersionScopeRouteWithChildren
  '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteWithChildren
  '/_sidebar/businesses/$businessId/model/$version/$scope/inputs': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsRouteWithChildren
  '/_sidebar/businesses/$businessId/model/$version/$scope/': typeof SidebarBusinessesBusinessIdModelVersionScopeIndexRoute
  '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/$productName': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute
  '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/$inputId': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute
  '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/': typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute
  '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/': typeof SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/businesses'
    | '/help'
    | '/industries'
    | '/profile'
    | '/settings'
    | '/businesses/$businessId'
    | '/businesses/new'
    | '/help/$topic'
    | '/industries/new'
    | '/businesses/'
    | '/help/'
    | '/industries/'
    | '/businesses/$businessId/edit'
    | '/businesses/$businessId/explorer'
    | '/businesses/$businessId/runs'
    | '/businesses/$businessId/'
    | '/businesses/$businessId/model/$version'
    | '/businesses/$businessId/runs/$runId'
    | '/businesses/$businessId/runs/new'
    | '/businesses/$businessId/runs/'
    | '/businesses/$businessId/model/$version/$scope'
    | '/businesses/$businessId/model/$version/$scope/$domainName'
    | '/businesses/$businessId/model/$version/$scope/inputs'
    | '/businesses/$businessId/model/$version/$scope/'
    | '/businesses/$businessId/model/$version/$scope/$domainName/$productName'
    | '/businesses/$businessId/model/$version/$scope/inputs/$inputId'
    | '/businesses/$businessId/model/$version/$scope/$domainName/'
    | '/businesses/$businessId/model/$version/$scope/inputs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/settings'
    | '/'
    | '/businesses/new'
    | '/help/$topic'
    | '/industries/new'
    | '/businesses'
    | '/help'
    | '/industries'
    | '/businesses/$businessId/edit'
    | '/businesses/$businessId/explorer'
    | '/businesses/$businessId'
    | '/businesses/$businessId/model/$version'
    | '/businesses/$businessId/runs/$runId'
    | '/businesses/$businessId/runs/new'
    | '/businesses/$businessId/runs'
    | '/businesses/$businessId/model/$version/$scope'
    | '/businesses/$businessId/model/$version/$scope/$domainName/$productName'
    | '/businesses/$businessId/model/$version/$scope/inputs/$inputId'
    | '/businesses/$businessId/model/$version/$scope/$domainName'
    | '/businesses/$businessId/model/$version/$scope/inputs'
  id:
    | '__root__'
    | '/_sidebar'
    | '/_sidebar/businesses'
    | '/_sidebar/help'
    | '/_sidebar/industries'
    | '/_sidebar/profile'
    | '/_sidebar/settings'
    | '/_sidebar/'
    | '/_sidebar/businesses/$businessId'
    | '/_sidebar/businesses/new'
    | '/_sidebar/help/$topic'
    | '/_sidebar/industries/new'
    | '/_sidebar/businesses/'
    | '/_sidebar/help/'
    | '/_sidebar/industries/'
    | '/_sidebar/businesses/$businessId/edit'
    | '/_sidebar/businesses/$businessId/explorer'
    | '/_sidebar/businesses/$businessId/runs'
    | '/_sidebar/businesses/$businessId/'
    | '/_sidebar/businesses/$businessId/model/$version'
    | '/_sidebar/businesses/$businessId/runs/$runId'
    | '/_sidebar/businesses/$businessId/runs/new'
    | '/_sidebar/businesses/$businessId/runs/'
    | '/_sidebar/businesses/$businessId/model/$version/$scope'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/inputs'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/$productName'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/$inputId'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/'
    | '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/businesses': {
      id: '/_sidebar/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof SidebarBusinessesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/help': {
      id: '/_sidebar/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof SidebarHelpRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/industries': {
      id: '/_sidebar/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof SidebarIndustriesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/settings': {
      id: '/_sidebar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarSettingsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/businesses/': {
      id: '/_sidebar/businesses/'
      path: '/'
      fullPath: '/businesses/'
      preLoaderRoute: typeof SidebarBusinessesIndexRouteImport
      parentRoute: typeof SidebarBusinessesRoute
    }
    '/_sidebar/businesses/$businessId': {
      id: '/_sidebar/businesses/$businessId'
      path: '/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdRouteImport
      parentRoute: typeof SidebarBusinessesRoute
    }
    '/_sidebar/businesses/new': {
      id: '/_sidebar/businesses/new'
      path: '/new'
      fullPath: '/businesses/new'
      preLoaderRoute: typeof SidebarBusinessesNewRouteImport
      parentRoute: typeof SidebarBusinessesRoute
    }
    '/_sidebar/help/': {
      id: '/_sidebar/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof SidebarHelpIndexRouteImport
      parentRoute: typeof SidebarHelpRoute
    }
    '/_sidebar/help/$topic': {
      id: '/_sidebar/help/$topic'
      path: '/$topic'
      fullPath: '/help/$topic'
      preLoaderRoute: typeof SidebarHelpTopicRouteImport
      parentRoute: typeof SidebarHelpRoute
    }
    '/_sidebar/industries/': {
      id: '/_sidebar/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof SidebarIndustriesIndexRouteImport
      parentRoute: typeof SidebarIndustriesRoute
    }
    '/_sidebar/industries/new': {
      id: '/_sidebar/industries/new'
      path: '/new'
      fullPath: '/industries/new'
      preLoaderRoute: typeof SidebarIndustriesNewRouteImport
      parentRoute: typeof SidebarIndustriesRoute
    }
    '/_sidebar/businesses/$businessId/': {
      id: '/_sidebar/businesses/$businessId/'
      path: '/'
      fullPath: '/businesses/$businessId/'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdIndexRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRoute
    }
    '/_sidebar/businesses/$businessId/edit': {
      id: '/_sidebar/businesses/$businessId/edit'
      path: '/edit'
      fullPath: '/businesses/$businessId/edit'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdEditRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRoute
    }
    '/_sidebar/businesses/$businessId/explorer': {
      id: '/_sidebar/businesses/$businessId/explorer'
      path: '/explorer'
      fullPath: '/businesses/$businessId/explorer'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdExplorerRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRoute
    }
    '/_sidebar/businesses/$businessId/runs': {
      id: '/_sidebar/businesses/$businessId/runs'
      path: '/runs'
      fullPath: '/businesses/$businessId/runs'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdRunsRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRoute
    }
    '/_sidebar/businesses/$businessId/model/$version': {
      id: '/_sidebar/businesses/$businessId/model/$version'
      path: '/model/$version'
      fullPath: '/businesses/$businessId/model/$version'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRoute
    }
    '/_sidebar/businesses/$businessId/runs/': {
      id: '/_sidebar/businesses/$businessId/runs/'
      path: '/'
      fullPath: '/businesses/$businessId/runs/'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdRunsIndexRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRunsRoute
    }
    '/_sidebar/businesses/$businessId/runs/$runId': {
      id: '/_sidebar/businesses/$businessId/runs/$runId'
      path: '/$runId'
      fullPath: '/businesses/$businessId/runs/$runId'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdRunsRunIdRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRunsRoute
    }
    '/_sidebar/businesses/$businessId/runs/new': {
      id: '/_sidebar/businesses/$businessId/runs/new'
      path: '/new'
      fullPath: '/businesses/$businessId/runs/new'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdRunsNewRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdRunsRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope'
      path: '/$scope'
      fullPath: '/businesses/$businessId/model/$version/$scope'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/'
      path: '/'
      fullPath: '/businesses/$businessId/model/$version/$scope/'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeIndexRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName'
      path: '/$domainName'
      fullPath: '/businesses/$businessId/model/$version/$scope/$domainName'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/inputs': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/inputs'
      path: '/inputs'
      fullPath: '/businesses/$businessId/model/$version/$scope/inputs'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/'
      path: '/'
      fullPath: '/businesses/$businessId/model/$version/$scope/$domainName/'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/$productName': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/$domainName/$productName'
      path: '/$productName'
      fullPath: '/businesses/$businessId/model/$version/$scope/$domainName/$productName'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/'
      path: '/'
      fullPath: '/businesses/$businessId/model/$version/$scope/inputs/'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsRoute
    }
    '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/$inputId': {
      id: '/_sidebar/businesses/$businessId/model/$version/$scope/inputs/$inputId'
      path: '/$inputId'
      fullPath: '/businesses/$businessId/model/$version/$scope/inputs/$inputId'
      preLoaderRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRouteImport
      parentRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsRoute
    }
  }
}

interface SidebarBusinessesBusinessIdRunsRouteChildren {
  SidebarBusinessesBusinessIdRunsRunIdRoute: typeof SidebarBusinessesBusinessIdRunsRunIdRoute
  SidebarBusinessesBusinessIdRunsNewRoute: typeof SidebarBusinessesBusinessIdRunsNewRoute
  SidebarBusinessesBusinessIdRunsIndexRoute: typeof SidebarBusinessesBusinessIdRunsIndexRoute
}

const SidebarBusinessesBusinessIdRunsRouteChildren: SidebarBusinessesBusinessIdRunsRouteChildren =
  {
    SidebarBusinessesBusinessIdRunsRunIdRoute:
      SidebarBusinessesBusinessIdRunsRunIdRoute,
    SidebarBusinessesBusinessIdRunsNewRoute:
      SidebarBusinessesBusinessIdRunsNewRoute,
    SidebarBusinessesBusinessIdRunsIndexRoute:
      SidebarBusinessesBusinessIdRunsIndexRoute,
  }

const SidebarBusinessesBusinessIdRunsRouteWithChildren =
  SidebarBusinessesBusinessIdRunsRoute._addFileChildren(
    SidebarBusinessesBusinessIdRunsRouteChildren,
  )

interface SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteChildren {
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute
}

const SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteChildren: SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteChildren =
  {
    SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute:
      SidebarBusinessesBusinessIdModelVersionScopeDomainNameProductNameRoute,
    SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute:
      SidebarBusinessesBusinessIdModelVersionScopeDomainNameIndexRoute,
  }

const SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteWithChildren =
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute._addFileChildren(
    SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteChildren,
  )

interface SidebarBusinessesBusinessIdModelVersionScopeInputsRouteChildren {
  SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute
  SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute
}

const SidebarBusinessesBusinessIdModelVersionScopeInputsRouteChildren: SidebarBusinessesBusinessIdModelVersionScopeInputsRouteChildren =
  {
    SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute:
      SidebarBusinessesBusinessIdModelVersionScopeInputsInputIdRoute,
    SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute:
      SidebarBusinessesBusinessIdModelVersionScopeInputsIndexRoute,
  }

const SidebarBusinessesBusinessIdModelVersionScopeInputsRouteWithChildren =
  SidebarBusinessesBusinessIdModelVersionScopeInputsRoute._addFileChildren(
    SidebarBusinessesBusinessIdModelVersionScopeInputsRouteChildren,
  )

interface SidebarBusinessesBusinessIdModelVersionScopeRouteChildren {
  SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteWithChildren
  SidebarBusinessesBusinessIdModelVersionScopeInputsRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeInputsRouteWithChildren
  SidebarBusinessesBusinessIdModelVersionScopeIndexRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeIndexRoute
}

const SidebarBusinessesBusinessIdModelVersionScopeRouteChildren: SidebarBusinessesBusinessIdModelVersionScopeRouteChildren =
  {
    SidebarBusinessesBusinessIdModelVersionScopeDomainNameRoute:
      SidebarBusinessesBusinessIdModelVersionScopeDomainNameRouteWithChildren,
    SidebarBusinessesBusinessIdModelVersionScopeInputsRoute:
      SidebarBusinessesBusinessIdModelVersionScopeInputsRouteWithChildren,
    SidebarBusinessesBusinessIdModelVersionScopeIndexRoute:
      SidebarBusinessesBusinessIdModelVersionScopeIndexRoute,
  }

const SidebarBusinessesBusinessIdModelVersionScopeRouteWithChildren =
  SidebarBusinessesBusinessIdModelVersionScopeRoute._addFileChildren(
    SidebarBusinessesBusinessIdModelVersionScopeRouteChildren,
  )

interface SidebarBusinessesBusinessIdModelVersionRouteChildren {
  SidebarBusinessesBusinessIdModelVersionScopeRoute: typeof SidebarBusinessesBusinessIdModelVersionScopeRouteWithChildren
}

const SidebarBusinessesBusinessIdModelVersionRouteChildren: SidebarBusinessesBusinessIdModelVersionRouteChildren =
  {
    SidebarBusinessesBusinessIdModelVersionScopeRoute:
      SidebarBusinessesBusinessIdModelVersionScopeRouteWithChildren,
  }

const SidebarBusinessesBusinessIdModelVersionRouteWithChildren =
  SidebarBusinessesBusinessIdModelVersionRoute._addFileChildren(
    SidebarBusinessesBusinessIdModelVersionRouteChildren,
  )

interface SidebarBusinessesBusinessIdRouteChildren {
  SidebarBusinessesBusinessIdEditRoute: typeof SidebarBusinessesBusinessIdEditRoute
  SidebarBusinessesBusinessIdExplorerRoute: typeof SidebarBusinessesBusinessIdExplorerRoute
  SidebarBusinessesBusinessIdRunsRoute: typeof SidebarBusinessesBusinessIdRunsRouteWithChildren
  SidebarBusinessesBusinessIdIndexRoute: typeof SidebarBusinessesBusinessIdIndexRoute
  SidebarBusinessesBusinessIdModelVersionRoute: typeof SidebarBusinessesBusinessIdModelVersionRouteWithChildren
}

const SidebarBusinessesBusinessIdRouteChildren: SidebarBusinessesBusinessIdRouteChildren =
  {
    SidebarBusinessesBusinessIdEditRoute: SidebarBusinessesBusinessIdEditRoute,
    SidebarBusinessesBusinessIdExplorerRoute:
      SidebarBusinessesBusinessIdExplorerRoute,
    SidebarBusinessesBusinessIdRunsRoute:
      SidebarBusinessesBusinessIdRunsRouteWithChildren,
    SidebarBusinessesBusinessIdIndexRoute:
      SidebarBusinessesBusinessIdIndexRoute,
    SidebarBusinessesBusinessIdModelVersionRoute:
      SidebarBusinessesBusinessIdModelVersionRouteWithChildren,
  }

const SidebarBusinessesBusinessIdRouteWithChildren =
  SidebarBusinessesBusinessIdRoute._addFileChildren(
    SidebarBusinessesBusinessIdRouteChildren,
  )

interface SidebarBusinessesRouteChildren {
  SidebarBusinessesBusinessIdRoute: typeof SidebarBusinessesBusinessIdRouteWithChildren
  SidebarBusinessesNewRoute: typeof SidebarBusinessesNewRoute
  SidebarBusinessesIndexRoute: typeof SidebarBusinessesIndexRoute
}

const SidebarBusinessesRouteChildren: SidebarBusinessesRouteChildren = {
  SidebarBusinessesBusinessIdRoute:
    SidebarBusinessesBusinessIdRouteWithChildren,
  SidebarBusinessesNewRoute: SidebarBusinessesNewRoute,
  SidebarBusinessesIndexRoute: SidebarBusinessesIndexRoute,
}

const SidebarBusinessesRouteWithChildren =
  SidebarBusinessesRoute._addFileChildren(SidebarBusinessesRouteChildren)

interface SidebarHelpRouteChildren {
  SidebarHelpTopicRoute: typeof SidebarHelpTopicRoute
  SidebarHelpIndexRoute: typeof SidebarHelpIndexRoute
}

const SidebarHelpRouteChildren: SidebarHelpRouteChildren = {
  SidebarHelpTopicRoute: SidebarHelpTopicRoute,
  SidebarHelpIndexRoute: SidebarHelpIndexRoute,
}

const SidebarHelpRouteWithChildren = SidebarHelpRoute._addFileChildren(
  SidebarHelpRouteChildren,
)

interface SidebarIndustriesRouteChildren {
  SidebarIndustriesNewRoute: typeof SidebarIndustriesNewRoute
  SidebarIndustriesIndexRoute: typeof SidebarIndustriesIndexRoute
}

const SidebarIndustriesRouteChildren: SidebarIndustriesRouteChildren = {
  SidebarIndustriesNewRoute: SidebarIndustriesNewRoute,
  SidebarIndustriesIndexRoute: SidebarIndustriesIndexRoute,
}

const SidebarIndustriesRouteWithChildren =
  SidebarIndustriesRoute._addFileChildren(SidebarIndustriesRouteChildren)

interface SidebarRouteRouteChildren {
  SidebarBusinessesRoute: typeof SidebarBusinessesRouteWithChildren
  SidebarHelpRoute: typeof SidebarHelpRouteWithChildren
  SidebarIndustriesRoute: typeof SidebarIndustriesRouteWithChildren
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarSettingsRoute: typeof SidebarSettingsRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarBusinessesRoute: SidebarBusinessesRouteWithChildren,
  SidebarHelpRoute: SidebarHelpRouteWithChildren,
  SidebarIndustriesRoute: SidebarIndustriesRouteWithChildren,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarSettingsRoute: SidebarSettingsRoute,
  SidebarIndexRoute: SidebarIndexRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
