-- DDL for Business:  | Version: 1 | Generated on: 2026-03-04 13:29:09

CREATE CATALOG IF NOT EXISTS `feip_eastus_03`;

-- ========= DATABASES (DOMAINS) =========
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`highway` COMMENT 'Core highway operations including roadway construction, maintenance, pavement management, and highway performance monitoring. Manages the state highway system infrastructure, roadway assets, and maintenance activities aligned with FHWA HPMS standards. Encompasses DOH functions for state highway system operations and preservation.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`dmv` COMMENT 'Division of Motor Vehicles providing citizen-facing services for driver licensing (DL, CDL), vehicle registration, titling, and regulatory oversight. Manages driver records (SADLS), vehicle titling and registration (STARS), motor vehicle records (MVR), and inspection programs (NCVIP).';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`bridge` COMMENT 'Bridge and structures management including inspection, maintenance, rehabilitation, and structural integrity monitoring. Implements NBIS standards, maintains NBI data, and manages the Bridge Management System (BMS) for state-owned bridges across the network.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`traffic` COMMENT 'Traffic management and operations including signal systems, ITS infrastructure, ATMS, TMC operations, incident management (IMAP), and traffic control devices per MUTCD standards. Manages AADT, VMT, LOS metrics and traffic flow analytics.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`project` COMMENT 'Transportation project management including STIP/TIP programming, project delivery, preliminary engineering (PE), construction engineering (CE), and project lifecycle tracking through SAP PS and HiCAMS systems.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`ferry` COMMENT 'Ferry operations and marine transportation services including vessel management, sailing schedules, route operations, terminal facilities, and maritime maintenance. Operates the second-largest state ferry system in the United States.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`transit` COMMENT 'Public transit coordination, funding administration, and multimodal transportation services. Manages FTA grant programs, transit system support, and coordination with MPO/RPO planning organizations for statewide transit service.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`aviation` COMMENT 'Aviation regulation, airport facilities management, airport system planning, and safety oversight. Provides regulatory oversight and funding coordination for public airports across North Carolina in alignment with FAA standards.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`rail` COMMENT 'Rail regulation, safety oversight, rail infrastructure coordination, and railroad crossing safety. Manages FRA compliance, track inspection programs, and coordination for freight and passenger rail operations.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`asset` COMMENT 'Enterprise asset management including equipment inventory, fleet management, facility assets, and lifecycle tracking through SAP PM and ATLAS systems. Manages asset condition, maintenance schedules, and capital asset accounting.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`rightofway` COMMENT 'Right-of-way acquisition, property management, real estate transactions, appraisals, and ROW corridor management. Manages land acquisition processes, easements, and property records through SAP RE module.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`environmental` COMMENT 'Environmental compliance and permitting for transportation projects including NEPA documentation (EIS, EA, CE, FONSI), Section 404 Clean Water Act permits, and coordination with SHPO, USACE, NCDEQ for environmental stewardship.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`safety` COMMENT 'Safety and incident management including emergency response, IMAP operations, crash data analysis, HSIP program administration, and coordination with GHSP for highway safety initiatives and traffic incident management.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`planning` COMMENT 'Statewide transportation planning including LRTP, CTP development, transportation modeling, mobility strategy, and coordination with MPO/RPO organizations for long-range multimodal transportation planning and programming.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`maintenance` COMMENT 'Maintenance operations for state transportation infrastructure including roadway maintenance, MOT activities, pavement preservation, vegetation management, work order management (SAP PM), and winter weather operations.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`grant` COMMENT 'Grants and federal programs administration including FHWA, FTA, BUILD, INFRA, RAISE, and TIFIA funding. Manages federal funding compliance, OMB Uniform Guidance (2 CFR 200), grant reporting, and reimbursement processes.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`finance` COMMENT 'Finance and budget management including financial accounting through SAP FI/CO, NCFS integration, budget planning, cost center management, GASB compliance, and governmental financial reporting for state and federal fiscal years.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`procurement` COMMENT 'Procurement and contracts management including vendor management, DBE/MBE/WBE/HUB programs, materials management through SAP MM, contract administration, letting processes, RFP/RFQ/IFB solicitations, and QA/QC oversight.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`hr` COMMENT 'Human resources management including workforce planning, employee records through Beacon and SAP HR, payroll administration, benefits management, training, and organizational development for NCDOT staff across all divisions.';
CREATE DATABASE IF NOT EXISTS `feip_eastus_03`.`gis` COMMENT 'Geographic Information Systems providing spatial data management, mapping services, location-based analysis, and geospatial infrastructure through ArcGIS Enterprise supporting all NCDOT transportation planning and operations functions.';