"""Contract tests — verify field alignment across the triple model pattern.

For every entity, the contract is:
  - Every non-relationship, non-auto-generated field on a DB model must appear
    on its corresponding Out model.
  - Every field on an In model must exist on the DB model.

This catches drift between layers: if a field is added to the DB model but
forgotten in the Out model, the API silently drops it. If a field is added
to the In model but not the DB model, writes silently ignore it.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src", "app", "src"))

import pytest
from pydantic import BaseModel

from vibe_modeling.backend import db_models as db
from vibe_modeling.backend import models as api


# Fields auto-generated by SQLModel/SQLAlchemy and not expected in API models
AUTO_FIELDS = {"id", "created_at", "updated_at"}

# Relationship fields in SQLModel (defined via Relationship(), not Column())
# These are ORM-level navigation properties, not DB columns
RELATIONSHIP_FIELDS = {
    "Business": {"contexts", "runs", "versions", "industry", "sector"},
    "BusinessContext": {"business"},
    "ModelVersion": {"business", "runs", "domains", "products", "fk_links"},
    "Run": {"business", "version", "events", "artifacts"},
    "RunProgressEvent": {"run"},
    "RunArtifact": {"run"},
    "Domain": {"version", "products"},
    "Product": {"version", "domain", "attributes"},
    "Attribute": {"product"},
    "ForeignKeyLink": {"version"},
    "AgentConfig": set(),
    "Industry": set(),
    "UserPreference": set(),
    "DiagramLayout": set(),
    "VibeInput": {"context_links", "run_links"},
    "VibeInputContextLink": {"input"},
    "RunInputLink": {"input"},
    "Subdomain": set(),
    "ProductReview": set(),
    "RunElementLineage": set(),
}

# Fields that are intentionally present in the DB but not in the Out model
# (internal implementation details not exposed via API)
DB_ONLY_FIELDS = {
    "Business": {"industry_id"},  # FK to industries table, resolved via industry_alignment string
    "BusinessContext": set(),
    "ModelVersion": set(),
    "Run": {"vibe_session_id_bigint", "last_consumed_step_id"},
    "RunProgressEvent": set(),
    "RunArtifact": set(),
    # GitHub config columns are exposed via the dedicated GithubConfigOut /
    # /config/github surface (ADR D-049), not on AgentConfigOut.
    "AgentConfig": {
        "github_repo_owner", "github_repo_name", "github_auth_mode",
        "github_connection_name", "github_secret_scope", "github_secret_key",
        # Upstream release-monitor cache (Surface 2): exposed via AgentCompatOut
        # / /config/agent-compat, not on AgentConfigOut.
        "upstream_release_version", "upstream_agent_version",
        "upstream_checked_at", "upstream_check_error",
    },
    "Industry": set(),
    "UserPreference": {"user_id"},  # user_id is derived from auth headers, not in Out
}


def _get_model_fields(model_cls) -> set[str]:
    """Extract field names from a Pydantic or SQLModel class."""
    if hasattr(model_cls, "model_fields"):
        return set(model_cls.model_fields.keys())
    return set()


def _db_api_fields(db_cls, relationship_names: set) -> set[str]:
    """Get DB model fields minus auto-generated and relationship fields."""
    all_fields = _get_model_fields(db_cls)
    return all_fields - AUTO_FIELDS - relationship_names


# ---------------------------------------------------------------------------
# DB → Out coverage tests
# ---------------------------------------------------------------------------


class TestDbToOutCoverage:
    """Every non-auto, non-relationship DB field should appear on the Out model."""

    @pytest.mark.parametrize("db_cls,out_cls,entity_name", [
        (db.Business, api.BusinessOut, "Business"),
        (db.BusinessContext, api.BusinessContextOut, "BusinessContext"),
        (db.ModelVersion, api.ModelVersionOut, "ModelVersion"),
        (db.Run, api.RunOut, "Run"),
        (db.RunProgressEvent, api.ProgressEventOut, "RunProgressEvent"),
        (db.RunArtifact, api.RunArtifactOut, "RunArtifact"),
        (db.AgentConfig, api.AgentConfigOut, "AgentConfig"),
        (db.Industry, api.IndustryOut, "Industry"),
        (db.UserPreference, api.UserPreferenceOut, "UserPreference"),
        # Vibe Inputs redesign (Task 2) — DB↔Out alignment. The VibeInput
        # entry is what forces the new `author` column onto VibeInputOut.
        (db.VibeInput, api.VibeInputOut, "VibeInput"),
        (db.VibeInputContextLink, api.VibeInputContextLinkOut, "VibeInputContextLink"),
        (db.RunInputLink, api.RunInputLinkOut, "RunInputLink"),
        (db.Subdomain, api.SubdomainOut, "Subdomain"),
        (db.ProductReview, api.ProductReviewOut, "ProductReview"),
        (db.RunElementLineage, api.RunElementLineageOut, "RunElementLineage"),
    ])
    def test_db_fields_covered_by_out(self, db_cls, out_cls, entity_name):
        db_fields = _db_api_fields(db_cls, RELATIONSHIP_FIELDS.get(entity_name, set()))
        out_fields = _get_model_fields(out_cls)
        db_only = DB_ONLY_FIELDS.get(entity_name, set())

        missing = db_fields - out_fields - db_only
        assert not missing, (
            f"{entity_name}: DB fields {missing} not in Out model {out_cls.__name__}. "
            f"Add them to the Out model or to DB_ONLY_FIELDS if intentionally omitted."
        )


# ---------------------------------------------------------------------------
# In → DB coverage tests
# ---------------------------------------------------------------------------


class TestModelVersionProvenanceMapping:
    """v_0_7_0: agent_version/release_version assemble DB→Out at read time."""

    def test_values_map_through(self):
        mv = db.ModelVersion(
            business_id="biz-1",
            version=1,
            agent_version="4.9.8",
            release_version="0.8.0",
        )
        out = api.ModelVersionOut.model_validate(mv, from_attributes=True)
        assert out.agent_version == "4.9.8"
        assert out.release_version == "0.8.0"

    def test_null_maps_to_none(self):
        mv = db.ModelVersion(business_id="biz-1", version=1)
        out = api.ModelVersionOut.model_validate(mv, from_attributes=True)
        assert out.agent_version is None
        assert out.release_version is None


class TestSyncStateContract:
    """B2: ModelVersionOut carries sync_state + sync_error_text, and the
    sync_state vocabulary includes sync_empty (no data / 0-domain payload)."""

    def test_out_exposes_sync_state_and_error_text(self):
        out_fields = _get_model_fields(api.ModelVersionOut)
        assert "sync_state" in out_fields
        assert "sync_error_text" in out_fields

    @pytest.mark.parametrize("value", [
        "ok", "incomplete_metadata", "sync_empty", "finalize_failed",
    ])
    def test_sync_state_accepts_vocabulary(self, value):
        mv = db.ModelVersion(business_id="biz-1", version=1, sync_state=value)
        out = api.ModelVersionOut.model_validate(mv, from_attributes=True)
        assert out.sync_state == value

    def test_sync_empty_error_text_maps_through(self):
        mv = db.ModelVersion(
            business_id="biz-1", version=1,
            sync_state="sync_empty", sync_error_text="No model data found",
        )
        out = api.ModelVersionOut.model_validate(mv, from_attributes=True)
        assert out.sync_state == "sync_empty"
        assert out.sync_error_text == "No model data found"


class TestInToDbCoverage:
    """Every In model field should exist on the corresponding DB model."""

    @pytest.mark.parametrize("in_cls,db_cls,entity_name", [
        (api.BusinessIn, db.Business, "Business"),
        (api.BusinessContextIn, db.BusinessContext, "BusinessContext"),
        (api.RunIn, db.Run, "Run"),
        (api.AgentConfigIn, db.AgentConfig, "AgentConfig"),
        (api.IndustryIn, db.Industry, "Industry"),
        (api.UserPreferenceIn, db.UserPreference, "UserPreference"),
        # Vibe Inputs redesign (Task 2). VibeInputIn carries transient anchor
        # fields (version_id, element ids) that the create endpoint folds into
        # an origin context link — auto-tolerated by the transient discovery.
        (api.VibeInputIn, db.VibeInput, "VibeInput"),
        (api.VibeInputContextLinkIn, db.VibeInputContextLink, "VibeInputContextLink"),
        (api.ReviewMarkIn, db.ProductReview, "ProductReview"),
    ])
    def test_in_fields_exist_on_db(self, in_cls, db_cls, entity_name):
        in_fields = _get_model_fields(in_cls)
        db_fields = _get_model_fields(db_cls)

        # Auto-discover transient In fields: anything without a matching SQLAlchemy
        # column on the DB table is handled outside the direct column mapping
        # (e.g. RunIn widget params folded into parameters_json, link-table IDs).
        db_columns = {c.name for c in db_cls.__table__.columns}
        transient = in_fields - db_columns

        missing = in_fields - db_fields - transient

        assert not missing, (
            f"{entity_name}: In model fields {missing} not found on DB model. "
            f"Either add them to the DB model or they need explicit mapping logic."
        )


# ---------------------------------------------------------------------------
# RunOperation schema lock — Phase 1 orchestrator refactor
# ---------------------------------------------------------------------------


class TestRunOperationSchema:
    """Phase 1 of the orchestrator refactor: `run_operations` table is
    persisted but not yet exposed via In/Out models. These tests pin the
    column shape so a later phase that adds RunOperationOut starts from a
    known-stable DB schema. They also catch accidental column drops in
    the gap between Phase 1 and Phase 4.

    Spec: docs/orchestrator-design.md §5.2.
    """

    def test_run_operations_table_exists(self):
        assert hasattr(db, "RunOperation"), (
            "RunOperation SQLModel must be defined in db_models.py — "
            "Phase 1 of the orchestrator refactor."
        )
        assert db.RunOperation.__tablename__ == "run_operations"

    def test_run_operations_columns_match_spec(self):
        expected = {
            "id", "run_id", "step_index", "operation_name",
            "params_json", "skip_if", "status",
            "databricks_run_id", "vibe_session_id",
            "parent_version_id", "output_version_id",
            "rollback_state_json", "error_message",
            "started_at", "completed_at", "created_at",
            "dispatched_widgets_json",
        }
        actual = {c.name for c in db.RunOperation.__table__.columns}
        assert expected == actual, (
            f"RunOperation columns drifted from §5.2 spec. "
            f"Missing: {expected - actual}; extra: {actual - expected}."
        )

    def test_run_operations_unique_constraint(self):
        """One op per step per run — orchestrator's start() relies on
        this to keep advance() retry-safe."""
        constraints = db.RunOperation.__table__.constraints
        unique_pairs = set()
        for c in constraints:
            cls_name = type(c).__name__
            if cls_name == "UniqueConstraint":
                unique_pairs.add(tuple(sorted(col.name for col in c.columns)))
        assert ("run_id", "step_index") in unique_pairs, (
            "RunOperation must have UNIQUE(run_id, step_index) — see §5.2."
        )

    def test_run_operations_run_id_indexed(self):
        """The orchestrator's poll loop queries by run_id; without an
        index it'd table-scan once per run on every advance() call."""
        run_id_col = db.RunOperation.__table__.c.run_id
        assert run_id_col.index, (
            "run_operations.run_id must be indexed for the orchestrator's "
            "poll-loop query."
        )

    def test_run_intent_column_exists(self):
        """Phase 5 retires ``run_type`` and ``rollback_plan`` in favour of
        ``Run.intent`` and per-step ``RunOperation.rollback_state_json``
        (orchestrator-design.md §5.1)."""
        col_names = {c.name for c in db.Run.__table__.columns}
        assert "intent" in col_names, "Run.intent must be persisted."
        assert "run_type" not in col_names, (
            "Run.run_type was retired in Phase 5; do not re-add it."
        )
        assert "rollback_plan" not in col_names, (
            "Run.rollback_plan was retired in Phase 5; rollback state "
            "now lives on RunOperation.rollback_state_json."
        )


# ---------------------------------------------------------------------------
# parameters_json shape — cataloging_style honoured for deployment_catalog
# ---------------------------------------------------------------------------


class TestParamsJsonDeploymentCatalogHelper:
    """The form's ``deployment_catalog`` field is meaningless in
    multi-catalog modes (the agent derives per-domain / per-division
    catalogs). The shared helper strips it from ``parameters_json`` so
    the run-detail audit trail isn't misleading.
    """

    @pytest.fixture
    def helper(self):
        from vibe_modeling.backend.routes._helpers import (
            params_json_omit_deployment_catalog_for_multi_catalog,
        )
        return params_json_omit_deployment_catalog_for_multi_catalog

    def test_one_catalog_keeps_deployment_catalog(self, helper):
        params = {"deployment_catalog": "main", "schema_prefix": "ecm_"}
        out = helper(params, "One Catalog")
        assert out["deployment_catalog"] == "main"

    def test_catalog_per_division_strips_deployment_catalog(self, helper):
        params = {"deployment_catalog": "main", "schema_prefix": ""}
        out = helper(params, "Catalog per Division")
        assert "deployment_catalog" not in out
        assert out["schema_prefix"] == ""

    def test_catalog_per_domain_strips_deployment_catalog(self, helper):
        params = {"deployment_catalog": "main", "catalog_prefix": "vibe_"}
        out = helper(params, "Catalog per Domain")
        assert "deployment_catalog" not in out
        assert out["catalog_prefix"] == "vibe_"

    def test_none_style_defaults_to_one_catalog(self, helper):
        params = {"deployment_catalog": "main"}
        out = helper(params, None)
        assert out["deployment_catalog"] == "main"

    def test_empty_string_style_defaults_to_one_catalog(self, helper):
        params = {"deployment_catalog": "main"}
        out = helper(params, "  ")
        assert out["deployment_catalog"] == "main"

    def test_idempotent_when_field_already_absent(self, helper):
        params = {"schema_prefix": ""}
        out = helper(params, "Catalog per Domain")
        assert "deployment_catalog" not in out
        assert "schema_prefix" in out
# an internal tracker item — RunArtifactOut.run_id must accept None
# ---------------------------------------------------------------------------


class TestRunArtifactOutRunIdOptional:
    """Lock the v_0_5_0 widening of ``RunArtifactOut.run_id`` to ``Optional[str]``.

    Imported ModelVersions write RunArtifact rows with ``run_id=NULL``
    (imports are syncs, not runs). Before the widen, the
    ``/api/model-versions/{id}/artifacts`` endpoint returned HTTP 500 with
    a Pydantic ``response[*].run_id: Input should be a valid string``
    error whenever any artifact in the response had a null run_id. The
    flow-level coverage lives in
    ``test_artifact_content.py::TestArtifactListByVersionWithNullRunId``;
    this contract test pins the type annotation so a future model edit
    that re-narrows the field is caught at the layer of the schema, not
    only at the endpoint.
    """

    def test_run_id_annotation_accepts_none(self):
        from typing import Union, get_args, get_origin

        field = api.RunArtifactOut.model_fields["run_id"]
        ann = field.annotation
        # ``Optional[str]`` is ``Union[str, None]`` — accept either spelling.
        if get_origin(ann) is Union:
            assert type(None) in get_args(ann), (
                f"RunArtifactOut.run_id must accept None; got annotation {ann!r}."
            )
        else:
            raise AssertionError(
                f"RunArtifactOut.run_id must be Optional[str] (Union[str, None]); "
                f"got non-Union annotation {ann!r}."
            )

    def test_run_id_default_is_none(self):
        """Default must be ``None`` so callers constructing an instance
        from an import row (run_id absent) don't have to pass it explicitly."""
        field = api.RunArtifactOut.model_fields["run_id"]
        assert field.default is None, (
            f"RunArtifactOut.run_id default must be None; got {field.default!r}."
        )

    def test_instance_with_null_run_id_validates(self):
        """End-to-end: an import-shaped row (run_id=None) must validate
        cleanly. Pre-widen, this raised ValidationError; the test would
        go red and surface the regression directly at the Pydantic layer
        rather than via a 500 in the artifacts endpoint."""
        from datetime import datetime, timezone

        instance = api.RunArtifactOut(
            id="art-1",
            run_id=None,
            model_version_id="mv-1",
            artifact_type="model_json",
            file_path="/Volumes/c/m/imports/model.json",
            created_at=datetime.now(timezone.utc),
        )
        assert instance.run_id is None


# ---------------------------------------------------------------------------
# Vibe Inputs redesign (Task 2) — enum lockstep, unique constraints, lineage
# ---------------------------------------------------------------------------


def _unique_column_tuples(table) -> set[tuple[str, ...]]:
    """Collect UNIQUE constraints off a SQLModel ``__table__`` as sorted
    column-name tuples — the same idiom as
    ``TestRunOperationSchema.test_run_operations_unique_constraint``."""
    out: set[tuple[str, ...]] = set()
    for c in table.constraints:
        if type(c).__name__ == "UniqueConstraint":
            out.add(tuple(sorted(col.name for col in c.columns)))
    return out


class TestVibeInputPriorityEnumLockstep:
    """R1: ``VibeInputPriority`` is the canonical priority vocabulary, and
    ``NextVibeItem.priority`` is retyped to it so the two cannot drift —
    they are the same symbol. A structural identity assertion is the
    lockstep; a value-set check is kept as a sanity guard on the vocabulary.
    """

    def test_next_vibe_item_priority_is_canonical_enum(self):
        ann = api.NextVibeItem.model_fields["priority"].annotation
        assert ann is api.VibeInputPriority, (
            "NextVibeItem.priority must be typed as VibeInputPriority (the "
            "canonical priority enum) so the two cannot drift — see "
            "task2-lakebase-schema.md §0.3/§3.1."
        )

    def test_priority_vocabulary(self):
        assert {e.value for e in api.VibeInputPriority} == {"high", "medium", "low"}

    def test_next_vibe_item_priority_default(self):
        assert api.NextVibeItem.model_fields["priority"].default == api.VibeInputPriority.HIGH
        assert api.NextVibeItem(id="nv-1", title="t").priority.value == "high"

    def test_next_vibe_item_priority_from_input_row(self):
        from vibe_modeling.backend.db_models import VibeInput
        from vibe_modeling.backend.routes._helpers import _next_vibe_item_from_input

        high = _next_vibe_item_from_input(
            VibeInput(business_id="b", text="t\n\nd", priority="high")
        )
        low = _next_vibe_item_from_input(
            VibeInput(business_id="b", text="t\n\nd", priority="low")
        )
        assert high.priority == api.VibeInputPriority.HIGH
        assert low.priority == api.VibeInputPriority.LOW

    def test_vibe_input_in_default_priority(self):
        assert api.VibeInputIn(text="x").priority == api.VibeInputPriority.MEDIUM


class TestVibeInputEnumVocabularies:
    def test_origin_values(self):
        assert {e.value for e in api.VibeInputOrigin} == {"user", "agent_next_vibe"}

    def test_status_values(self):
        assert {e.value for e in api.VibeInputStatus} == {"active", "deprecated"}

    def test_next_vibe_category_values(self):
        assert {e.value for e in api.NextVibeCategory} == {
            "static_analysis", "priority_remediation", "other"
        }

    def test_category_field_on_out_and_db(self):
        """The agent next-vibe classification is a structured field (nullable
        column + Out projection), not a text convention. v_0_6_3."""
        assert "category" in _get_model_fields(api.VibeInputOut)
        assert "category" in {c.name for c in db.VibeInput.__table__.columns}


class TestNextVibeMetricsOut:
    """T13: the next_vibes "expected work" metrics wire shape. Read-only
    aggregate Out models — no DB/In counterpart, so this is a pure shape +
    enum-alignment lock."""

    def test_metrics_out_shape(self):
        fields = _get_model_fields(api.NextVibeMetricsOut)
        assert fields == {
            "version_id", "domain_id", "quality_score",
            "counts", "total_open", "has_data",
        }

    def test_counts_keys_track_category_enum(self):
        """The per-category counts Out must carry one field per
        ``NextVibeCategory`` value (plus ``total``) — so a new category can't
        be added to the enum without surfacing here. Guards drift between the
        classification vocabulary and the metrics shape."""
        count_fields = _get_model_fields(api.NextVibeCategoryCountsOut)
        category_values = {e.value for e in api.NextVibeCategory}
        assert category_values <= count_fields
        assert count_fields == category_values | {"total"}

    def test_degraded_default_is_no_data(self):
        """A bare instance models the pre-ingestion default: zeros, null score,
        has_data=False."""
        m = api.NextVibeMetricsOut(version_id="v1")
        assert m.has_data is False
        assert m.total_open == 0
        assert m.quality_score is None
        assert m.domain_id is None
        assert m.counts.total == 0


class TestKickstartInContract:
    """Track 3: the kickstart request carries an opt-out ``copy_inputs`` flag
    defaulting True (a kickstart inherits the industry's curation)."""

    def test_copy_inputs_present_and_defaults_true(self):
        from vibe_modeling.backend.routes.industry_models import KickstartIn

        fields = _get_model_fields(KickstartIn)
        assert "copy_inputs" in fields
        m = KickstartIn(source_version=1, new_name="Acme")
        assert m.copy_inputs is True
        assert m.whole_model is True  # unchanged default


class TestMetamodelSeedConvergence:
    """Track 3 spike lock: EVERY iterable-version producer must seed
    ``_metamodel`` (else the produced version is un-iterable - the agent reads
    its parent model only from ``_metamodel``). All four converge on the single
    shared ``seed_metamodel_one`` helper, which is the one place that calls the
    canonical ``write_metamodel``. Static source checks so a new producer that
    forgets to seed, or a refactor that drops a call, fails here rather than
    silently shipping an un-iterable version. Mirrors the next-vibes lock."""

    def test_all_producers_call_shared_seed_helper(self):
        import inspect

        from vibe_modeling.backend.routes import import_root
        from vibe_modeling.backend.routes import businesses as businesses_route
        from vibe_modeling.backend.services import (
            industry_download,
            industry_kickstart,
        )

        for mod in (
            import_root,          # import model.json
            businesses_route,     # Volume-import (execute_import)
            industry_kickstart,   # kickstart
            industry_download,    # download
        ):
            # Require the CALL syntax, not just the symbol, so dropping the
            # actual call while leaving the import/comment still fails here.
            assert "seed_metamodel_one(" in inspect.getsource(mod), (
                f"{mod.__name__} must seed _metamodel via seed_metamodel_one() - "
                f"an iterable-version producer that does not seed makes its "
                f"version un-iterable."
            )

    def test_shared_helper_calls_write_metamodel(self):
        """The convergence point actually calls the canonical writer - keep the
        write_metamodel( call-syntax lock here now that the four producers
        delegate to the shared helper."""
        import inspect

        from vibe_modeling.backend.services import import_metamodel_writer

        src = inspect.getsource(import_metamodel_writer.seed_metamodel_one)
        assert "write_metamodel(" in src

    def test_service_producers_bind_seed_helper_at_module_level(self):
        """Import-honesty: the two service producers use a MODULE-LEVEL import,
        so the name must be bound on the module (a missing import would 500 at
        runtime with NameError - and must not be masked by a test patching the
        attribute into existence)."""
        from vibe_modeling.backend.services import (
            industry_download,
            industry_kickstart,
        )

        assert callable(getattr(industry_kickstart, "seed_metamodel_one", None))
        assert callable(getattr(industry_download, "seed_metamodel_one", None))


class TestVibeInputUniqueConstraints:
    """R2: lock the v1 anchoring/review uniqueness rules via
    ``__table__.constraints`` introspection (not live engine reflection)."""

    def test_context_link_unique_input_version(self):
        uniques = _unique_column_tuples(db.VibeInputContextLink.__table__)
        assert ("input_id", "version_id") in uniques, (
            "vibe_input_context_links must enforce UNIQUE(input_id, version_id) "
            "— one anchor per input per version in v1."
        )

    def test_product_review_unique_version_product(self):
        uniques = _unique_column_tuples(db.ProductReview.__table__)
        assert ("product_id", "version_id") in uniques, (
            "product_reviews must enforce UNIQUE(version_id, product_id) — one "
            "review marker per product per version."
        )


class TestElementLineageColumns:
    """N3 intent: the new lineage columns must exist on the element tables.

    There is no 1:1 ``DomainOut``/``ProductOut``/``AttributeOut``/
    ``ForeignKeyLinkOut`` model — the element Out models in this codebase are
    projection/diagram views (``DomainDetailOut``, ``ProductSummaryOut`` …)
    that deliberately omit row identity/FK columns. So the new
    ``previous_element_id`` / ``subdomain_id`` columns are correctly NOT on
    any Out model; this test pins their existence on the DB side so a future
    accidental drop is caught at the schema layer.
    """

    def test_previous_element_id_present(self):
        for model in (db.Domain, db.Product, db.Attribute, db.ForeignKeyLink, db.Subdomain):
            cols = {c.name for c in model.__table__.columns}
            assert "previous_element_id" in cols, (
                f"{model.__name__}.previous_element_id lineage column missing"
            )

    def test_product_subdomain_id_present(self):
        cols = {c.name for c in db.Product.__table__.columns}
        assert "subdomain_id" in cols
        # The transitional string column is kept alongside the FK.
        assert "subdomain" in cols



class TestTask5RequestResponseShapes:
    """Task 5 introduces request/response shapes with no 1:1 DB table. Pin
    their field sets so a silent contract break surfaces in CI."""

    def test_compile_shapes(self):
        assert _get_model_fields(api.CompileIn) == {"input_ids"}
        assert _get_model_fields(api.CompileOut) == {
            "markdown", "blocks", "included_input_ids",
            "excluded_input_ids", "excluded_reasons",
        }
        assert _get_model_fields(api.CompiledBlockOut) == {
            "input_id", "origin", "priority", "author",
            "confidence_score", "section_path", "text",
        }

    def test_carry_forward_result_shape(self):
        assert _get_model_fields(api.CarryForwardResultOut) == {
            "version_id", "auto_linked", "needs_review", "deprecated",
            "skipped_existing", "link_ids_needing_review",
        }

    def test_reanchor_in_matches_link_anchor_columns(self):
        anchor_cols = {
            "domain_id", "subdomain_id", "product_id", "attribute_id", "fk_link_id",
        }
        assert _get_model_fields(api.ReanchorIn) == anchor_cols

    def test_review_queue_shapes(self):
        assert _get_model_fields(api.ReviewQueueOut) == {"total", "items"}
        assert _get_model_fields(api.ReviewQueueItemOut) == {
            "link", "input", "proposed_anchor_label", "tier",
        }

    def test_run_in_carries_input_ids(self):
        assert "input_ids" in _get_model_fields(api.RunIn)

    def test_vibe_input_anchor_out_shape(self):
        assert _get_model_fields(api.VibeInputAnchorOut) == {
            "level",
            "domain_id", "domain_name",
            "subdomain_id", "subdomain_name",
            "product_id", "product_name",
            "attribute_id", "attribute_name",
            "fk_link_id", "fk_label",
            "path",
        }

    def test_vibe_input_out_carries_anchor(self):
        assert "anchor" in _get_model_fields(api.VibeInputOut)


class TestBusinessListOutTaxonomyFields:
    """Industry Management (ADR D-046/D-047): the list projection must carry
    both the ``kind`` discriminator and the ``sector_id`` FK so the Businesses
    + Industries list views resolve the Sector column and the Industry/Business
    label without a second per-row fetch. Pin them — dropping either silently
    blanks the list UI."""

    def test_business_list_out_carries_kind_and_sector_id(self):
        fields = _get_model_fields(api.BusinessListOut)
        assert "kind" in fields
        assert "sector_id" in fields

    def test_sector_in_out_field_shapes(self):
        assert _get_model_fields(api.SectorIn) == {
            "name", "short_name", "description", "display_order", "is_active",
        }
        assert _get_model_fields(api.SectorOut) == {
            "id", "name", "short_name", "description", "display_order",
            "is_active", "created_at", "updated_at",
        }


class TestBusinessListOutProvenance:
    """BusinessListOut must surface kickstart provenance so list views can
    render kickstart badges without an N+1 fetch of each BusinessOut.
    Mirrors the provenance fields already on BusinessOut + the DB row."""

    def test_list_out_exposes_provenance(self):
        list_fields = _get_model_fields(api.BusinessListOut)
        assert "source_industry_id" in list_fields
        assert "source_version" in list_fields

    def test_provenance_fields_align_with_db(self):
        db_fields = _get_model_fields(db.Business)
        assert "source_industry_id" in db_fields
        assert "source_version" in db_fields

    def test_provenance_types_match_business_out(self):
        list_fields = api.BusinessListOut.model_fields
        out_fields = api.BusinessOut.model_fields
        for name in ("source_industry_id", "source_version"):
            assert list_fields[name].annotation == out_fields[name].annotation


class TestCatalogSchemaWarningOut:
    """Shape lock for the co-located ``CatalogSchemaWarningOut`` response model.

    No DB / In counterpart — this is a computed-read-only endpoint. The lock
    ensures ``catalog``, ``schema_count``, and ``schemas`` are always present
    (the FE rendering and the test_catalog_schema_warning tests depend on them).
    """

    def test_shape(self):
        from vibe_modeling.backend.routes.uc_browse import CatalogSchemaWarningOut

        fields = _get_model_fields(CatalogSchemaWarningOut)
        assert fields == {"catalog", "schema_count", "schemas"}
