"""Tests for the GET /runs/{run_id}/artifacts/{artifact_id}/content endpoint."""

from unittest.mock import MagicMock

import pytest
from sqlmodel import Session

from vibe_modeling.backend.db_models import RunArtifact


def _seed_run_and_artifact(
    engine, business_id: str, file_path: str, artifact_type: str = "readme"
) -> tuple[str, str]:
    """Create a Run + RunArtifact. Returns (run_id, artifact_id)."""
    from vibe_modeling.backend.db_models import Run
    with Session(engine) as session:
        run = Run(
            business_id=business_id,
            intent="new-base-model",
            status="completed",
        )
        session.add(run)
        session.commit()
        session.refresh(run)

        artifact = RunArtifact(
            run_id=run.id,
            artifact_type=artifact_type,
            file_path=file_path,
        )
        session.add(artifact)
        session.commit()
        session.refresh(artifact)
        return run.id, artifact.id


def _mock_file_download(mock_ws, content: bytes):
    resp = MagicMock()
    resp.contents.read.return_value = content
    mock_ws.files.download.return_value = resp


class TestArtifactContentEndpoint:
    def test_read_markdown_artifact(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/docs/readme.md",
        )
        _mock_file_download(
            mock_ws, b"# Model Overview\n\nGenerated by mock agent.\n",
        )

        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 200, r.text
        data = r.json()
        assert data["content"].startswith("# Model Overview")
        assert data["truncated"] is False
        assert data["size_bytes"] > 0

    def test_read_json_artifact(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/model.json",
            artifact_type="json",
        )
        _mock_file_download(mock_ws, b'{"hello": "world"}')

        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 200
        assert '"hello"' in r.json()["content"]

    def test_binary_artifact_rejected_with_415(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/export.parquet",
        )
        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 415
        assert "parquet" in r.json()["detail"].lower()

    def test_hex_preview_for_binary_parquet(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/export.parquet",
        )
        raw = b"PAR1\x00\xffHELLO"
        _mock_file_download(mock_ws, raw)
        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content?format=hex"
        )
        assert r.status_code == 200, r.text
        data = r.json()
        assert "hex" in data
        assert data["hex"] == raw.hex()
        assert data["size_bytes"] == len(raw)
        assert data["bytes_previewed"] == len(raw)
        assert data["truncated"] is False

    def test_read_python_artifact(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/script.py",
        )
        _mock_file_download(mock_ws, b"def main():\n    print('ok')\n")
        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 200
        assert "def main" in r.json()["content"]

    def test_nonexistent_artifact_404(self, client_with_agent, seed_business, engine):
        bid = seed_business
        run_id, _ = _seed_run_and_artifact(engine, seed_business, "/Volumes/c/s/v/x.md")
        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/does-not-exist/content"
        )
        assert r.status_code == 404

    def test_artifact_from_wrong_run_404(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id_a, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/a.md",
        )
        run_id_b, _ = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/b.md",
        )
        # Request artifact from run A using run B's ID — should 404
        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id_b}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 404

    def test_truncation_reports_size(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        """Files over 500KB should be truncated with a size_bytes indicator."""
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/big.json",
        )
        big_content = b"x" * (600 * 1024)  # 600 KB
        _mock_file_download(mock_ws, big_content)

        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 200
        data = r.json()
        assert data["truncated"] is True
        assert data["size_bytes"] == 600 * 1024
        # Returned content is capped at 500 KB
        assert len(data["content"]) <= 512 * 1024

    def test_invalid_utf8_returns_415(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/bad.txt",
        )
        _mock_file_download(mock_ws, b"\xff\xfe\x00invalid utf-8")

        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 415
        assert "UTF-8" in r.json()["detail"]

    def test_download_failure_returns_502(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        run_id, artifact_id = _seed_run_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/ok.md",
        )
        mock_ws.files.download.side_effect = RuntimeError("volume unreachable")

        r = client_with_agent.get(
            f"/api/businesses/{bid}/runs/{run_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 502
        assert "volume unreachable" in r.json()["detail"]


def _seed_imported_version_and_artifact(
    engine, business_id: str, file_path: str,
    artifact_type: str = "model_json",
    version: int = 1, scope: str = "mvm",
) -> tuple[str, str]:
    """Create an imported ModelVersion + RunArtifact with run_id=NULL.

    Mirrors the path the import-from-Volume flow takes: ModelVersion has
    ``import_source_path`` set; ``RunArtifact.run_id`` is NULL (since
    ``v_0_5_0`` made the column nullable for "imports are syncs, not runs").
    """
    from vibe_modeling.backend.db_models import ModelVersion
    with Session(engine) as session:
        mv = ModelVersion(
            business_id=business_id,
            version=version,
            status="completed",
            scope=scope,
            import_source_path="/Volumes/c/_metamodel/vol_root/imports/x/model.json",
        )
        session.add(mv)
        session.commit()
        session.refresh(mv)

        artifact = RunArtifact(
            run_id=None,
            model_version_id=mv.id,
            artifact_type=artifact_type,
            file_path=file_path,
        )
        session.add(artifact)
        session.commit()
        session.refresh(artifact)
        return mv.id, artifact.id


class TestArtifactContentByVersionEndpoint:
    """Per-version artifact preview — used by the Artifacts tab on imported
    model versions where ``run_id`` is NULL (see ``v_0_5_0`` migration).
    Mirrors the run-scoped surface but keyed on ``model_version_id``."""

    def test_read_imported_artifact_json(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        mv_id, artifact_id = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/model.json",
        )
        _mock_file_download(mock_ws, b'{"hello": "from-import"}')

        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_id}/artifacts/{artifact_id}/content"
        )
        assert r.status_code == 200, r.text
        data = r.json()
        assert "hello" in data["content"]
        assert data["truncated"] is False

    def test_read_imported_artifact_txt_hex(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        mv_id, artifact_id = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/vibes/next_vibes.txt",
            artifact_type="text",
        )
        _mock_file_download(mock_ws, b"PRIORITY 1\nDo X\n\nPRIORITY 2\nDo Y\n")

        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_id}/artifacts/{artifact_id}/content?format=hex"
        )
        assert r.status_code == 200, r.text
        data = r.json()
        assert "hex" in data and data["hex"].startswith("5052494f52495459")  # "PRIORITY"

    def test_nonexistent_artifact_404(
        self, client_with_agent, seed_business, engine
    ):
        bid = seed_business
        mv_id, _ = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/model.json",
        )
        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_id}/artifacts/00000000-0000-0000-0000-000000000000/content"
        )
        assert r.status_code == 404

    def test_artifact_from_wrong_version_404(
        self, client_with_agent, seed_business, engine
    ):
        bid = seed_business
        mv_a, art_a = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/a.json",
            version=1, scope="mvm",
        )
        mv_b, art_b = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/b.json",
            version=1, scope="ecm",
        )
        # Ask for artifact a under version b — must not leak.
        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_b}/artifacts/{art_a}/content"
        )
        assert r.status_code == 404


class TestArtifactListByVersionWithNullRunId:
    """Regression test for the HTTP 500 the user reported on 2026-05-18:
    /api/businesses/{bid}/model-versions/{id}/artifacts returned 500 because
    ``RunArtifactOut.run_id`` was typed ``str`` but imported rows have
    ``run_id=None``. Fix: ``RunArtifactOut.run_id: Optional[str] = None``.
    """

    def test_list_imported_artifacts_returns_200_with_null_run_id(
        self, client_with_agent, seed_business, engine
    ):
        bid = seed_business
        mv_id, art1 = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/m/imports/model.json",
        )
        # Add a couple more so the response list serialises all of them
        with Session(engine) as session:
            for path, atype in [
                ("/Volumes/c/m/imports/vibes/current_vibes.txt", "text"),
                ("/Volumes/c/m/imports/vibes/next_vibes.txt", "text"),
            ]:
                session.add(RunArtifact(
                    run_id=None, model_version_id=mv_id,
                    artifact_type=atype, file_path=path,
                ))
            session.commit()

        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_id}/artifacts"
        )
        assert r.status_code == 200, r.text
        rows = r.json()
        assert len(rows) == 3
        for row in rows:
            assert row["run_id"] is None
            assert row["model_version_id"] == mv_id


class TestArtifactDownloadByVersionEndpoint:
    def test_download_imported_artifact(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        mv_id, artifact_id = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/model.json",
        )
        _mock_file_download(mock_ws, b'{"hello": "from-import"}')

        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_id}/artifacts/{artifact_id}/download"
        )
        assert r.status_code == 200, r.text
        assert r.content == b'{"hello": "from-import"}'
        assert "attachment" in r.headers.get("content-disposition", "")
        assert "model.json" in r.headers.get("content-disposition", "")

    def test_download_inline_png(
        self, client_with_agent, mock_ws, seed_business, engine
    ):
        bid = seed_business
        mv_id, artifact_id = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/diagram.png",
            artifact_type="image",
        )
        _mock_file_download(mock_ws, b"\x89PNG\r\n\x1a\n")

        r = client_with_agent.get(
            f"/api/businesses/{bid}/model-versions/{mv_id}/artifacts/{artifact_id}/download?inline=true"
        )
        assert r.status_code == 200, r.text
        assert r.headers["content-type"] == "image/png"
        assert "inline" in r.headers.get("content-disposition", "")


class TestPerVersionArtifactBusinessTenancy:
    """Tenancy gate on the four per-version artifact endpoints.

    The endpoints nest under ``/businesses/{business_id}/model-versions/...``;
    if the version exists but belongs to a different business, every
    endpoint must collapse to 404 (matching the run-scoped sibling's
    "Run not found" behaviour) so existence isn't leaked across tenants.
    """

    @pytest.fixture
    def _two_businesses(self, engine):
        from vibe_modeling.backend.db_models import Business

        with Session(engine) as session:
            a = Business(name="Biz A")
            b = Business(name="Biz B")
            session.add(a)
            session.add(b)
            session.commit()
            session.refresh(a)
            session.refresh(b)
            return a.id, b.id

    def test_list_wrong_business_returns_404(
        self, client_with_agent, mock_ws, engine, _two_businesses
    ):
        bid_a, bid_b = _two_businesses
        mv_id, _ = _seed_imported_version_and_artifact(
            engine, bid_a, "/Volumes/c/s/v/imports/model.json",
        )
        r = client_with_agent.get(
            f"/api/businesses/{bid_b}/model-versions/{mv_id}/artifacts"
        )
        assert r.status_code == 404

    def test_download_zip_wrong_business_returns_404(
        self, client_with_agent, mock_ws, engine, _two_businesses
    ):
        bid_a, bid_b = _two_businesses
        mv_id, _ = _seed_imported_version_and_artifact(
            engine, bid_a, "/Volumes/c/s/v/imports/model.json",
        )
        r = client_with_agent.get(
            f"/api/businesses/{bid_b}/model-versions/{mv_id}/artifacts/download"
        )
        assert r.status_code == 404

    def test_content_wrong_business_returns_404(
        self, client_with_agent, mock_ws, engine, _two_businesses
    ):
        bid_a, bid_b = _two_businesses
        mv_id, art_id = _seed_imported_version_and_artifact(
            engine, bid_a, "/Volumes/c/s/v/imports/model.json",
        )
        r = client_with_agent.get(
            f"/api/businesses/{bid_b}/model-versions/{mv_id}/artifacts/{art_id}/content"
        )
        assert r.status_code == 404

    def test_download_single_wrong_business_returns_404(
        self, client_with_agent, mock_ws, engine, _two_businesses
    ):
        bid_a, bid_b = _two_businesses
        mv_id, art_id = _seed_imported_version_and_artifact(
            engine, bid_a, "/Volumes/c/s/v/imports/model.json",
        )
        r = client_with_agent.get(
            f"/api/businesses/{bid_b}/model-versions/{mv_id}/artifacts/{art_id}/download"
        )
        assert r.status_code == 404

    def test_nonexistent_business_returns_404(
        self, client_with_agent, seed_business, engine
    ):
        mv_id, art_id = _seed_imported_version_and_artifact(
            engine, seed_business, "/Volumes/c/s/v/imports/model.json",
        )
        for url in (
            f"/api/businesses/no-such-biz/model-versions/{mv_id}/artifacts",
            f"/api/businesses/no-such-biz/model-versions/{mv_id}/artifacts/download",
            f"/api/businesses/no-such-biz/model-versions/{mv_id}/artifacts/{art_id}/content",
            f"/api/businesses/no-such-biz/model-versions/{mv_id}/artifacts/{art_id}/download",
        ):
            r = client_with_agent.get(url)
            assert r.status_code == 404, (url, r.status_code)

    def test_nonexistent_version_returns_404(
        self, client_with_agent, seed_business
    ):
        bid = seed_business
        for url in (
            f"/api/businesses/{bid}/model-versions/no-such-mv/artifacts",
            f"/api/businesses/{bid}/model-versions/no-such-mv/artifacts/download",
            f"/api/businesses/{bid}/model-versions/no-such-mv/artifacts/x/content",
            f"/api/businesses/{bid}/model-versions/no-such-mv/artifacts/x/download",
        ):
            r = client_with_agent.get(url)
            assert r.status_code == 404, (url, r.status_code)
